### ISSUE TITLE
Tag selection and deselection is faulty

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/timemap#12]
Environment
-----------
Running Firefox 63.0.1 on Mac OS High Sierra.

Steps to reproduce (for bugs only)
-----------------------------
1. Run a version of timemaps with a hierarchy of tags. No events have been assigned tags.\
![screen shot 2018-11-05 at 17 40 50](https://user-images.githubusercontent.com/16495856/48015878-0b541e80-e122-11e8-875f-86da330fc328.png)

2. Open up a tag panel. In this case, the tag panel has three immediate children (but the bug seems pervasive across other tag setups).
![screen shot 2018-11-05 at 17 42 11](https://user-images.githubusercontent.com/16495856/48015929-2f176480-e122-11e8-8299-bce42b6c26fd.png)

3. Attempt to select the parent tag ('Soldiers').

Current Behavior
----------------
The box for the parent tag that has been selected is not highlighted to indicate that the tag filter is active. It does, however, seem to be selected 'behind the scenes', as if I close and open the tag panel or selected one of the children tags, the box for 'Soldiers' seems to become selected. 

Expected Behavior
-----------------
The box corresponding to the parent tag should be highlighted immediately when it is selected. This issue seems to exist in grandchildren tags as well: when I try to select a grandchild tag, it does not even become highlighted when closing and opening the panel.

Another bug that I noticed while testing this: if I select a tag that contains no events, it removes all events from the map (as expected). If I then deselect that tag, however, there remain no events on the screen. All events should return to the map after deselecting, as no selected tags should show all events.

**Comment by francamps** [comment]
There is an implicit design decision here that is not resolved, and was implicitly coherent within the context of the Ayotzinapa case: the expectation that tags are unique (they were in Ayotzinapa).

Currently, tags have two functions: i) to characterize events by adding some consistent labels to them (tags are shown on Cards), ii) to filter in and out by checking boxes from the tag panels on the Toolbar, as well as searching through bundles of events grouped by those. 

A - If we decide to make individual tags being unique, I would say there should be a check that messages and enforces it.

B - If tags don't have to be unique, then the ways these tags are displayed as metadata for each event needs to be rethought, maybe by displaying each tag's entire lineage.

I don't think there is a right or wrong solution here, but rather a design choice that needs to be messaged properly.

**Comment by breezykermo** [comment]
I'm still having issues with a local instance after these changes. I think it's because the code assumes that all tags are unique, rather than keeping separate namespaces for each tag tree. For example, I've created two tag trees as follows:
```
Soldiers
 - bob
 - alice
 - tom
```
```
Civilians
 - bob
 - - tom
 - - alice
```

When I open up the `Civilians` tag panel and attempt to toggle the `bob` tag from off to on, nothing happens. 
![screen shot 2018-11-07 at 10 50 40](https://user-images.githubusercontent.com/16495856/48127194-08207600-e27b-11e8-8130-85d229bc56cd.png)

If I then open up the `Soldiers` panel, however, the `bob` tag that is a child there has been selected.
![screen shot 2018-11-07 at 10 51 34](https://user-images.githubusercontent.com/16495856/48127256-2be3bc00-e27b-11e8-985c-39c8a6c26b4a.png)

We need to find a more elegant solution for this (or at the very least document it as a bug) before merging.

**Comment by francamps** [comment]
There is an implicit design decision here that is not resolved, and was implicitly coherent within the context of the Ayotzinapa case: the expectation that tags are unique (they were in Ayotzinapa).
​
Currently, tags have two functions: i) to characterize events by adding some consistent labels to them (tags are shown on Cards), ii) to filter in and out by checking boxes from the tag panels on the Toolbar, as well as searching through bundles of events grouped by those.
​
A - If we decide to make individual tags being unique, I would say there should be a check that messages and enforces it.
​
B - If tags don't have to be unique, then the ways these tags are displayed as metadata for each event needs to be rethought, maybe by displaying each tag's entire lineage.
​
I don't think there is a right or wrong solution here, but rather a design choice that needs to be messaged properly.

**Comment by francamps** [comment]
Some more thinking about this.

On first thought, non-unique tags (NUTs?) seem like a more generalized case than UTs, since it is possible to imagine individuals sharing a first name, for example. 

On second thought, I think UTs are more effective at what they do, which is, apologies for the obviousness, to tag. The fact that they are part of a hierarchy is a bit of an add-on to this concept, and if they don't tag uniquely, then that they are no longer tags but rather a different entity with somewhat different properties.

In the case of NUTs, an alternative way of thinking about them is to consider the full lineage of the tag as what needs to be unique (tag + all its ancestors), but that would in fact require a way not only to display them as full lineages, but also to tag events with this full lineage or a reference to it, and it actually starts to look a lot like simply longer tags. For example, if an event is of the form:

```
  {
    "desc":"SOME DESCRIPTION TEXT",
    "date":"8/23/2011",
    "time":"18:30",
    "location":"LOCATION_NAME",
    "lat":"17.810358",
    "long":"-18.2251664",
    "source":"",
    "tags": "",
    "category": ""
  },
```

The property `tags` then needs to be an array of ids, or something of the like, since the individual tags are no longer unambiguous. If we would then expect the full lineage to be there at every instance of the tag, then that is no different than NUTs.

For the time being, my preference would be to lean towards enforcing UTs. This will require enforcing some type of validation and error handling, which is currently lacking. Unless there is an urgent need for NUTs, I would issue NUTs as a future feature, with _uniqueness_ something that can be set by the user.

**Comment by breezykermo** [comment]
Right. NUT tags that exist in a hierarchy are sort of more like filepaths, where there is a surface-level representation that is not unique (the local filename), but always an underlying absolute path that must necessarily be unique, otherwise you would have duplicate tags in the same level of the hierarchy.

My concern is that, if we are enforcing unique names for _local_ tags, then why is the tree structure necessary? Given that tags are locally unique at all levels, the tree structure becomes confusing. My understanding of why we had the tree structure in the first place was to hierarchize tags throug parent-child relationships: in which NUT tags make a lot more sense. Otherwise the tree structure is only meaningful for _displaying_ the tags, rather than as a hierarchical data structure. If we enforce UT tags, I would advocate to flatten the data structure of tags to 'soften' their representation, and simply add an attribute to tags that relates them to other tags.

Or is there a way in which the tree structure is meaningful beyond display if all tags are unique that I'm not considering?

**Comment by francamps** [comment]
Right, mostly the one advantage the tree structure has is one of ux, to be able to filter by groupings, groupings that are legible and intuitive. For example, for an organization of people, this allows to select all events that have been tagged with any individual or any team / section belonging to Organization A. People in an organization should only appear once. My sense based on using this kind of UI before is that this can be useful for the viewer, and also intuitive to a user who is trying to understand sequences and events.

I can see how these UT tree structures can look somewhat confusing as data structure on first thought, but I see it as a particular case of a general tree structure. I see the challenge of making the particularity of the case visible and valid.

That said, I see why in some cases you may want some tags to be available in separate parts of a hierarchy. 

In order to not keep get stuck in this convo, and given that right now we do, in practical terms, have a UT system, I suggest the following action items:

i) Make this issue about messaging and clarifying that this is currently a requirement: tags need to be globally unique.

ii) Make a _separate_ issue for a future feature to allow NUTs, or locally unique tags.

**Comment by breezykermo** [comment]
That sounds good to me -- with the addition that we should _enforce_ global uniqueness in the code, and not accept incoming tag structures that don't abide (in the same way that we reject poorly formatted events).

**Comment by francamps** [comment]
Sounds good. I've added a check for duplicate leaf tags in the validator. Once it finds a duplicate, it removes it from the tree (duplicate tag is ignored) and a notification is triggered. See PR #14 

<img width="1125" alt="screen shot 2018-11-08 at 11 53 43 am" src="https://user-images.githubusercontent.com/1273180/48215608-9d416e80-e350-11e8-8e1a-0451295a9f50.png">
