### ISSUE TITLE
All SVGs rendered on domain/app update

### ISSUE THREAD

**Issue by breezykermo** [forensic-architecture/timemap#53]
There is a lot that could be improved about the handoff from the React component hierarchy to the `map.js` and `timeline.js` classes, which implement d3 logic using selectors.

These classes current have initialisation logic that is called in the `componentDidMount` of proxy React wrapper components, as well as `render` and `update` functions that are called conditionally in the `componentWillReceiveProps` method.

The problem with this is that we lose the benefit of React's [reconciliation](https://reactjs.org/docs/reconciliation.html) algorithm when the Redux store updates, requiring **all** SVGs to be re-rendered in both the timeline and the map on any change.

The fix for this problem will require a relatively hefty refactor of the d3 logic in those two classes, to better make use of the caching we get when using React components. Essentially, what is needed is _a refactor of timeline.js and map.js into a range of React components that render the equivalent SVG markup_.

**Comment by francamps** [comment]
I have been thinking that this is a good idea and we can work on it progressively. It will be an interesting route to go, and there is some low hanging fruit on reactifying parts of map.js and timeline.js. I would say based on the discussion that map.js is more urgent than timeline.js since it operates on svg via js a lot more, and it generally contains more elements.

I agree that leveraging the reconociliation benefits to avoid rerenders can help us. There will be some things that we might want Leaflet (or Mapbox GL) and d3 to handle, in terms of scales, transforms and animations, but we can start for example with the svg itself and the site labels and go from there.
